import type { SkyMode } from './worldTypes';

/** Device-local rendering preferences. They never change network or paint authority. */
export interface RenderSettings { heightLod:boolean; lodHeightThreshold:number; shortDetailDistance:number; shortProxyDistance:number; shortFlatDistance:number; tallDetailDistance:number; tallProxyDistance:number; tallFlatDistance:number; lampActivationDistance:number; lampFadeDistance:number; renderScale: number; fogDensity: number; horizonDistance: number; horizon: boolean; scenery: boolean; streamBudgetMs: number; retentionSeconds: number; liveStrokeDistance: number; detailDistance:number; skylineDistance:number; skylineMinHeight:number; skylineWidth:number; skyline:boolean; exposure:number; groundChunks:number; groundExtension:boolean; groundColor:string; fogStyle:'exp'|'linear'; fogNear:number; fogFar:number; fogCull:boolean; skyMatch:boolean; flatSky:boolean; skyMode:SkyMode|'game'; customFog:boolean; fogColor:string; ambientScale:number; sunScale:number; streetLights:boolean; lampPools:boolean; lampCount:number; lampIntensity:number; lampDistance:number; lampRadius:number; playerLight:boolean; playerLightIntensity:number; imageLoadDistance:number; imageConcurrency:number; prefetchDistance:number }
export const MAX_STREET_LIGHTS = 32;
export const DEFAULT_RENDER_SETTINGS: Readonly<RenderSettings> = Object.freeze({ heightLod:true,lodHeightThreshold:12,shortDetailDistance:48,shortProxyDistance:68,shortFlatDistance:160,tallDetailDistance:60,tallProxyDistance:84,tallFlatDistance:400,lampActivationDistance:60,lampFadeDistance:0, renderScale: 1.2, fogDensity: .06, horizonDistance: 68, horizon: true, scenery: true, streamBudgetMs: 1.5, retentionSeconds: 3, liveStrokeDistance: 5, detailDistance:69, skylineDistance:400, skylineMinHeight:5, skylineWidth:1, skyline:true, exposure:1.5, groundChunks:4,groundExtension:true,groundColor:'#8b8982',fogStyle:'exp',fogNear:20,fogFar:200,fogCull:false,skyMatch:true,flatSky:false,skyMode:'game',customFog:false,fogColor:'#111b2c',ambientScale:5,sunScale:3,streetLights:true,lampPools:true,lampCount:12,lampIntensity:150,lampDistance:40,lampRadius:12,playerLight:true,playerLightIntensity:10,imageLoadDistance:35,imageConcurrency:1,prefetchDistance:12 });
const KEY='graffciti.render-settings.v1';
export function normaliseRenderSettings(value: unknown): RenderSettings {
  const v=(value && typeof value==='object' ? value : {}) as Partial<RenderSettings>;
  const number=(key:keyof RenderSettings,min:number,max:number)=>typeof v[key]==='number'&&Number.isFinite(v[key])?Math.max(min,Math.min(max,v[key] as number)):DEFAULT_RENDER_SETTINGS[key] as number;
  const boolean=(key:keyof RenderSettings)=>typeof v[key]==='boolean'?v[key] as boolean:DEFAULT_RENDER_SETTINGS[key] as boolean;
  const color=(key:'fogColor'|'groundColor')=>typeof v[key]==='string'&&/^#[0-9a-f]{6}$/i.test(v[key] as string)?v[key] as string:DEFAULT_RENDER_SETTINGS[key];
  const fogNear=number('fogNear',0,1198),fogFar=Math.max(fogNear+1,number('fogFar',1,1199));
  const shortDetailDistance=number('shortDetailDistance',4,144),shortProxyDistance=Math.max(shortDetailDistance,number('shortProxyDistance',0,768)),shortFlatDistance=Math.max(shortProxyDistance,number('shortFlatDistance',0,1152));
  const tallDetailDistance=number('tallDetailDistance',4,144),tallProxyDistance=Math.max(tallDetailDistance,number('tallProxyDistance',0,768)),tallFlatDistance=Math.max(tallProxyDistance,number('tallFlatDistance',0,1152));
  return {heightLod:boolean('heightLod'),lodHeightThreshold:number('lodHeightThreshold',1,80),shortDetailDistance,shortProxyDistance,shortFlatDistance,tallDetailDistance,tallProxyDistance,tallFlatDistance,lampActivationDistance:number('lampActivationDistance',2,120),lampFadeDistance:number('lampFadeDistance',0,30), renderScale:number('renderScale',.35,3), fogDensity:number('fogDensity',0,.2), horizonDistance:number('horizonDistance',48,768), horizon:typeof v.horizon==='boolean'?v.horizon:true, scenery:typeof v.scenery==='boolean'?v.scenery:true, streamBudgetMs:number('streamBudgetMs',.25,12), retentionSeconds:number('retentionSeconds',0,30), liveStrokeDistance:number('liveStrokeDistance',5,240), detailDistance:number('detailDistance',4,144), skylineDistance:number('skylineDistance',48,1152), skylineMinHeight:number('skylineMinHeight',5,56), skylineWidth:number('skylineWidth',.5,3), skyline:typeof v.skyline==='boolean'?v.skyline:true, exposure:number('exposure',.1,3),groundChunks:number('groundChunks',1,20),groundExtension:boolean('groundExtension'),groundColor:color('groundColor'),fogStyle:v.fogStyle==='linear'?'linear':'exp',fogNear,fogFar,fogCull:boolean('fogCull'),skyMatch:boolean('skyMatch'),flatSky:boolean('flatSky'),skyMode:['day','sunset','pastel','rain','night'].includes(v.skyMode as string)?v.skyMode as SkyMode:'game',customFog:boolean('customFog'),fogColor:color('fogColor'),ambientScale:number('ambientScale',0,5),sunScale:number('sunScale',0,5),streetLights:boolean('streetLights'),lampPools:boolean('lampPools'),lampCount:Math.round(number('lampCount',0,MAX_STREET_LIGHTS)),lampIntensity:number('lampIntensity',0,150),lampDistance:number('lampDistance',2,40),lampRadius:number('lampRadius',1,12),playerLight:boolean('playerLight'),playerLightIntensity:number('playerLightIntensity',0,50),imageLoadDistance:number('imageLoadDistance',3,240),imageConcurrency:Math.round(number('imageConcurrency',1,7)),prefetchDistance:number('prefetchDistance',0,24) };
}
function read(){try{return normaliseRenderSettings(JSON.parse(localStorage.getItem(KEY)??'null'));}catch{return {...DEFAULT_RENDER_SETTINGS};}}
let current=read(); const listeners=new Set<()=>void>();
export const getRenderSettings=()=>current;
export const subscribeRenderSettings=(listener:()=>void)=>{listeners.add(listener);return()=>{listeners.delete(listener);};};
export function setRenderSettings(patch:Partial<RenderSettings>){current=normaliseRenderSettings({...current,...patch});try{localStorage.setItem(KEY,JSON.stringify(current));}catch{/* Session preferences still work. */}listeners.forEach(listener=>listener());}
export const resetRenderSettings=()=>setRenderSettings({...DEFAULT_RENDER_SETTINGS});
